### ISSUE TITLE
Failed to download book cover jpg

### ISSUE THREAD

**Issue by powerman** [sgzmd/at2epub#2]
```
$ java -jar target/at2epub-1.0-SNAPSHOT-jar-with-dependencies.jar https://author.today/reader/97246 tmp.epub        
сен 04, 2021 11:09:16 PM StoryDownloader <init>
INFO: Initializing StoryDownloader...
Starting ChromeDriver 93.0.4577.15 (660fc11082ba57405eca2e8c49c3e1af756fbfae-refs/branch-heads/4577@{#203}) on port 9439
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1630786156.796][SEVERE]: bind() failed: Невозможно назначить запрошенный адрес (99)
ChromeDriver was started successfully.
сен 04, 2021 11:09:17 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
сен 04, 2021 11:09:17 PM StoryDownloader <init>
INFO: StoryDownloader initialized.
сен 04, 2021 11:09:18 PM ChromeDriverUtils checkPageIsLoaded
INFO: Checking page is loaded: true
сен 04, 2021 11:09:20 PM StoryDownloader getNextChapter
INFO: Url: https://author.today/reader/97246
сен 04, 2021 11:09:20 PM ChromeDriverUtils checkPageIsLoaded
INFO: Checking page is loaded: true
Exception in thread "main" javax.imageio.IIOException: Can't get input stream from URL!
	at javax.imageio.ImageIO.read(ImageIO.java:1401)
	at StoryDownloader.getNextChapter(StoryDownloader.kt:228)
	at StoryDownloader.downloadStory(StoryDownloader.kt:107)
	at ATDownloader$Companion.main(ATDownloader.kt:32)
	at ATDownloader.main(ATDownloader.kt)
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://author.today/content/2021/03/25/4cec64c8046c492cbe803ac8ab34b7f9.jpg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at java.net.URL.openStream(URL.java:1068)
	at javax.imageio.ImageIO.read(ImageIO.java:1399)
	... 4 more
```

Manually this url opens just fine, without 503.

**Comment by sgzmd** [comment]
I think this has to do with their anti-DDoS checks, which at2epub routinely doesn't pass. One way of solving it was pointing WebDriver to use a real Chrome profile which is more likely to pass said check.
